language: php

compiler:
  - gcc
  - clang

os:
  - linux

php:
  - 7.0
  - 7.1
  - 7.2

notifications:
  email: wjx@php.net

before_script:
  - sudo apt-get install libexpat1-dev -y
  - wget https://github.com/nih-at/libzip/archive/rel-1-5-1.tar.gz
  - tar -zxvf rel-1-5-1.tar.gz
  - cd libzip-rel-1-5-1 && midir build && cd build
  - cmake ..
  - make
  - make install
  - cd ../../
  - phpize && ./configure && make clean && make

branches:
  only:
    - master
    - develop
script:
    - ./travis/run-test.sh
