language: php

compiler:
  - gcc
  - clang

os:
  - linux

php:
  - 7.0
  - 7.1
  - 7.2

notifications:
  email: wjx@php.net

before_script:
  - sudo apt-get install libexpat1-dev -y
  - mkdir libzip_build && cd libzip_build && mkdir build
  - git clone https://github.com/nih-at/libzip.git && git checkout rel-1-5-1
  - cd build && cmake ..
  - make && make install && cd ../../
  - phpize && ./configure && make clean && make

branches:
  only:
    - master
    - develop
script:
    - ./travis/run-test.sh
